
# Don't print a new line at the start of the prompt
add_newline = false

scan_timeout = 10

# "custom.foo",
format = """\
[❰$username$hostname$directory$cmd_duration$status$jobs$git_state ❱](bold white bg:black) 
"""
right_format = """\
[❰$python$git_branch$git_commit${env_var.PWD}$time ❱](bold white bg:black)
"""
# ┃┣╸│├╴╳┇┋║╠═
# ⌈⌊⎛⎝⎞⎠⎡⎧⎩⎣⎬⎮
# 
# ∙
# ↑↳
#[ ](bg:black)[](black)
#[ ](none)
    # $cmd_duration\
    # $line_break\
    # $custom.charprefix\
    # $username\
    # $hostname\
    # $character\

# ❬❮❰❭❯❱
# 
# ∙ ⋅⋄∴∵∶∷∺−∗∘∙
# ¯¯¨‾
# •‣‧‹›

[username]
style_root = "bold red bg:black"
style_user = "bold green bg:black"
show_always = false
format = "[ $user]($style)"

[hostname]
ssh_only = true
format = "[@](bold green bg:black)[$hostname](bold green bg:black) "

[directory]
# TODO truncate length after repo root
repo_root_style = "blue"  # required to enable $repo_root_format
truncate_to_repo = true
truncation_length = 0
truncation_symbol = "…/"
read_only = ""
format = "[ $path](bold blue bg:black)([ $read_only](bold yellow bg:black))"
repo_root_format = "[ ⌥ $repo_root](bold blue bg:black)[$path](bold black bg:black)([ $read_only](bold yellow bg:black))"

[cmd_duration]
min_time = 1000
style = "bold black bg:black"
format = "[ $duration](bold black bg:black)"

[status]
format = "[ $status](bold red bg:black)"

[jobs]
number_threshold = 1
format = "[ $number](bold yellow bg:black)"

[git_state]
format = "[ $state($progress_current/$progress_total)](bold red bg:black)"

[python]
symbol = ""
pyenv_version_name = false
format = '[ $virtualenv](bold yellow bg:black)'

[git_branch]
style="bold purple bg:black"
only_attached = true
symbol=""
format="[ $branch](bold green bg:black)"

[git_commit]
commit_hash_length = 7
# TODO: always show tag if any
only_detached = false
tag_disabled = false
tag_symbol = ""
format="([ $tag](bold yellow bg:black))[ $hash](bold purple bg:black)"

[env_var.PWD]
default = "PWD"
style = "bold black bg:black"
format = "[ $env_value]($style)"

[time]
time_format = "%H:%M"
format = "[ $time](bold black bg:black)"
disabled = false
