
# Don't print a new line at the start of the prompt
add_newline = false

scan_timeout = 10

# "custom.foo",
format = """\
[$env_var❰$username$hostname$directory$jobs$git_state$cmd_duration$status ❱](bold white bg:black)[ ](none)
"""
    # $cmd_duration\
    # $line_break\
    # $custom.charprefix\
    # $username\
    # $hostname\
    # $character\

[env_var]
variable = "_STARSHIP_ENV_VAR"
style = "bg:black bold black"
format = "[$env_value]($style)"

[directory]
truncation_length = 1
truncate_to_repo = true
truncation_symbol = "…/"
fish_style_pwd_dir_length = 2
format = "[ $path](bold blue bg:black)([ $read_only](bold yellow bg:black))"
read_only = ""

# [directory.substitutions]
# "/dev/shm" = "SHM"

[username]
style_root = "bold red bg:black"
style_user = "bold blue bg:black"
show_always = false
format = "[ $user]($style)"

[hostname]
ssh_only = true
format = "[ @$hostname](bold green bg:black) "

[cmd_duration]
min_time = 500
# format = "[ ↳$duration↲](bold red bg:black)"
format = "[ $duration](bold black bg:black)"

[jobs]
threshold = 0
format = "[ $number](bold green bg:black)"

[git_state]
format = "[ $state($progress_current/$progress_total)](bold red bg:black)"

[character]
symbol = "❱"
style_success = "bold white"
style_error = "bold red"

[status]
style = "bg:black bold red"
format = '[ $status]($style)'
disabled = false

# [username]
# show_always = true
# style_user = "bold blue"
# style_root = "bold red"
# suffix = ""
# prefix = ""
