daemonize = true
max_history = 50
# history_file_path = '$XDG_RUNTIME_DIR/clipcatd/db'
# history_file_path = '/tmp/clipcatd/db'
log_level = 'INFO'

[monitor]
load_current = true
enable_clipboard = true
enable_primary = true

[grpc]
host = '127.0.0.1'
port = 45045
