daemonize = true
max_history = 500
history_file_path = '/run/user/1000/clipcat'
log_level = 'INFO'

[monitor]
load_current = true
enable_clipboard = true
enable_primary = true

[grpc]
host = '127.0.0.1'
port = 45045
